export const FETCH_PRODUCT='FETCH_PRODUCT'
export const ADD_PRODUCT='ADD_PRODUCT'
export const REMOVE_PRODUCT_FROMARRAY='REMOVE_PRODUCT_FROMARRAY'


// for cart component
export const ADD_PRODUCT_TO_CART='ADD_PRODUCT_TO_CART'
export const DECREASE_ITEM_COUNT='DECREASE_ITEM_COUNT'
export const DELETE_PRODUCT_FROM_CART='DELETE_PRODUCT_FROM_CART'


//for total
export const INCREASE_TOTAL='INCREASE_TOTAL'
export const DECREASE_TOTAL='DECREASE_TOTAL'
export const CALCULATE_TOTAL='CALCULATE_TOTAL'
export const REMOVE_DELETED_COST_FROM_TOTAL='REMOVE_DELETED_COST_FROM_TOTAL'